FROM python:3.9-alpine

ENV PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.2.0

RUN apk add --no-cache gcc libffi-dev musl-dev python3-dev mariadb-connector-c-dev
RUN pip install "poetry==$POETRY_VERSION"

WORKDIR /server
COPY poetry.lock pyproject.toml /server/

RUN poetry config virtualenvs.create false \
  && poetry install --no-interaction --no-ansi

COPY . /server/

CMD uvicorn server.main:app --host 0.0.0.0 --port 80 --reload