name: Client CI (ESLint, Expo EAS build)

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Check linting warnings and errors using ESLint
        run: |
          echo "Linting..."
          cd client
          npm run lint
          echo "Linting ended!"

      - name: Build on EAS
        run: |
          cd client
          eas build --platform android --non-interactive
