name: Client CD (Expo EAS build)

on:
  workflow_run:
    workflows: [Client CI (ESLint, Expo EAS build)]
    types:
      - completed
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build on EAS
        run: |
          cd client
          eas build --platform android --non-interactive --profile production
