name: Build, push server image into Docker Hub and deploy server into GKE

on:
  workflow_run:
    workflows: [Server CI (flake8, docker build, pytest)]
    types:
      - completed
  push:
    branches:
      - "*"

env:
  SHORT_SHA: $(echo ${{ github.sha }} | cut -c 1-8)

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Gcloud
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update && sudo apt-get install google-cloud-cli
          gcloud components install gke-gcloud-auth-plugin
          gcloud components install kubectl

      - name: Authenticate to Google Cloud and set cluster information
        env:
          USE_GKE_GCLOUD_AUTH_PLUGIN: True
        run: |
          echo ${{ secrets.SERVICE_ACCOUNT }} | base64 --decode > service-account.json
          gcloud auth activate-service-account --key-file service-account.json
          gcloud config set project ${{ secrets.GKE_PROJECT }}
          gcloud config set compute/zone ${{ secrets.GKE_ZONE }}
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }}
          kubectl get namespaces

      - name: Login to Docker
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build, tag, and push the image to Docker Hub
        id: build-image
        run: |
          # Build a docker container and push it to ECR 
          echo "Building server image..."
          cd server
          docker image build \
          --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest \
          --tag ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }} \
          .

          echo "Pushing image to ECR..."
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}:${{ env.SHORT_SHA }}

      - name: Make server deployment yaml from template
        run: |
          export DOCKER_REPOSITORY=${{ secrets.DOCKER_USERNAME }}/${{ secrets.IMAGE_NAME }}
          export IMAGE_TAG=${{ env.SHORT_SHA }}
          envsubst < kubernetes/templates/server-deployment.tmpl.yaml > kubernetes/server-deployment.yaml
          cat kubernetes/server-deployment.yaml

      - name: Terminate old deployments and services
        run: |
          kubectl delete all --all

      - name: Deploy
        run: |
          kubectl apply -f kubernetes

      - name: verify deployment
        run: |
          kubectl rollout status deployment/server-deployment
